name = "StenoGraphs"
uuid = "78862bba-adae-4a83-bb4d-33c106177f81"
authors = ["Aaron Peikert <aaron.peikert@posteo.de> and contributors"]
version = "0.2.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"

[targets]
test = ["Test", "SafeTestsets"]
